"use client";
export type CombatSettings={stance?:'stationary'|'ranged'|'melee';dodge_mode?:'key'|'move';minimum_distance?:number;attack_distance?:number;ranged_attack_distance?:number};
export type SteeringSettings={projection?:'isotropic'|'normalized';move_interval_ms?:number;require_minimap?:boolean;player_screen?:number[];infer_player_from_hud?:boolean};
export type MappingSettings={enabled:boolean;mode?:'bright_floor'|'wall_lines'|'hsv'|'diablo4_auto';center_weight?:number;preferred_clearance_px?:number;wall_margin_px?:number;calibrated?:boolean;screen_pixels_per_map_pixel?:number;crop_to_viewport?:boolean};

export default function GameplayControls({combat={},steering={},mapping,disabled=[],onDisabled,onCombat,onSteering,onMapping}:{combat?:CombatSettings;steering?:SteeringSettings;mapping?:MappingSettings;disabled?:string[];onDisabled:(actions:string[])=>void;onCombat:(patch:Partial<CombatSettings>)=>void;onSteering:(patch:Partial<SteeringSettings>)=>void;onMapping:(patch:Partial<MappingSettings>)=>void}){
 return <div><h4>게임별 이동·회피·전투</h4><label className="setting-row">전투 거리 방식<select value={combat.stance??'stationary'} onChange={e=>onCombat({stance:e.target.value as CombatSettings['stance']})}><option value="stationary">현재 대상 공격 유지</option><option value="ranged">원거리 캐릭터 · 거리 유지 후 공격</option><option value="melee">근거리 캐릭터 · 접근 후 공격</option></select></label><label className="setting-row">회피 방식<select value={combat.dodge_mode??'key'} onChange={e=>onCombat({dodge_mode:e.target.value as CombatSettings['dodge_mode']})}><option value="key">설정된 회피 키 사용</option><option value="move">이동으로 후퇴 · 회피 키 전송 안 함</option></select></label><label className="setting-row">원거리 최소 거리(화면 높이 %)<input type="number" min={5} max={60} value={(combat.minimum_distance??.18)*100} onChange={e=>onCombat({minimum_distance:Number(e.target.value)/100})}/></label><label className="setting-row">원거리 최대 공격 거리(화면 높이 %)<input type="number" min={5} max={60} value={(combat.ranged_attack_distance??.45)*100} onChange={e=>onCombat({ranged_attack_distance:Number(e.target.value)/100})}/></label><label className="setting-row">근접 공격 거리(화면 높이 %)<input type="number" min={5} max={60} value={(combat.attack_distance??.16)*100} onChange={e=>onCombat({attack_distance:Number(e.target.value)/100})}/></label>
 <label className="setting-row">이동 입력 최소 간격(ms)<input type="number" min={100} max={2000} step={50} value={steering.move_interval_ms??500} onChange={e=>onSteering({move_interval_ms:Number(e.target.value)})}/></label><p className="live-help">이동은 미니맵 통로를 확인한 경우에만 실행합니다. 전투 Qwen 분석이 오래되어도 지도 경로는 계속 갱신합니다.</p><label className="skill-enable"><input type="checkbox" checked={steering.infer_player_from_hud??false} onChange={e=>onSteering({infer_player_from_hud:e.target.checked})}/>플레이어 위 HP바에서 발 위치 보완</label><div className="binding-grid">{['캐릭터 발 위치 X(%)','캐릭터 발 위치 Y(%)'].map((label,i)=><label key={label}>{label}<input type="number" min={10} max={90} value={(steering.player_screen??[.5,.5])[i]*100} onChange={e=>onSteering({player_screen:(steering.player_screen??[.5,.5]).map((v,j)=>i===j?Number(e.target.value)/100:v)})}/></label>)}</div>
 {mapping?.enabled&&<><label className="skill-enable"><input type="checkbox" checked={mapping.crop_to_viewport??true} onChange={e=>onMapping({crop_to_viewport:e.target.checked})}/>검은 여백 제외 · 실제 게임 화면 기준 미니맵 좌표</label><label className="setting-row">미니맵 지형 표시<select value={mapping.mode??'bright_floor'} onChange={e=>onMapping({mode:e.target.value as MappingSettings['mode'],calibrated:e.target.value!=='wall_lines'})}><option value="diablo4_auto">디아블로 IV · 야외/어두운 던전 자동</option><option value="bright_floor">밝은 통로 · 진한 장애물</option><option value="wall_lines">벽 윤곽선 지도 · 색상 보정 필요</option><option value="hsv">설정한 통로 색상</option></select></label>{mapping.mode==='diablo4_auto'&&<p className="live-help">야외와 어두운 던전을 자동으로 구분합니다. 던전에서는 플레이어와 연결된 방·통로를 확인하며, 미확인 영역은 이동 경로에서 제외합니다.</p>}<label className="setting-row">지도 1px당 이동 클릭 거리(1080p 화면 px)<input type="number" min={2} max={40} step={.5} value={mapping.screen_pixels_per_map_pixel??12} onChange={e=>onMapping({screen_pixels_per_map_pixel:Number(e.target.value)})}/></label><p className="live-help">192px로 줄인 지도 기준입니다. 기본 12는 초기 추정값이며 게임 확대율에 맞춰 보정해야 합니다. 코너를 지나쳐 클릭하면 값을 낮추세요. 이동거리 %는 상한으로 적용합니다.</p><label className="setting-row">통로 중앙 선호도<input type="number" min={0} max={15} step={.5} value={mapping.center_weight??4} onChange={e=>onMapping({center_weight:Number(e.target.value)})}/></label><label className="setting-row">통로 중앙 여유 폭(192px 지도 기준)<input type="number" min={2} max={30} value={mapping.preferred_clearance_px??10} onChange={e=>onMapping({preferred_clearance_px:Number(e.target.value)})}/></label><label className="setting-row">벽 가장자리 제외 폭(192px 지도 기준)<input type="number" min={0} max={5} value={mapping.wall_margin_px??2} onChange={e=>onMapping({wall_margin_px:Number(e.target.value)})}/></label>{mapping.mode==='wall_lines'&&<label className="skill-enable"><input type="checkbox" checked={mapping.calibrated??false} onChange={e=>onMapping({calibrated:e.target.checked})}/>미니맵 벽 색상·영역을 확인하고 보정 확정</label>}</>}
 {(['USE_SKILL','CAST_BUFF'] as const).map(action=><label className="skill-enable" key={action}><input type="checkbox" checked={disabled.includes(action)} onChange={e=>onDisabled(e.target.checked?[...disabled.filter(a=>a!==action),action]:disabled.filter(a=>a!==action))}/>{action==='USE_SKILL'?'대화 명령 스킬':'버프'} 키 확인 전 입력 차단</label>)}<p className="live-help">막히면 중앙 복귀 → 지나온 길로 후퇴 → 다른 통로를 시도합니다. 4회 실패하면 이동을 보류합니다. 게임별 스킬·물약 키와 HUD는 따로 확인해야 합니다.</p></div>;
}
