"use client";
import {useEffect,useState} from "react";
import {Plus,Loader2} from "lucide-react";
import {toast} from "sonner";
type Game={id:string;name:string};
type Catalog={active:string;games:Game[]};
export default function GameTabs({active,online,call,onSelected}:{active:string;online:boolean;call:(path:string,method?:string,body?:unknown)=>Promise<unknown>;onSelected:(id:string)=>Promise<void>}){
 const [games,setGames]=useState<Game[]>([]),[adding,setAdding]=useState(false),[name,setName]=useState(""),[title,setTitle]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let live=true;setError("");if(online)void call("/v1/games").then(r=>{if(live)setGames((r as Catalog).games);}).catch(e=>{if(live)setError(e instanceof Error?e.message:"게임 목록을 읽지 못했습니다.");});return()=>{live=false;};},[online,active]);
 async function select(id:string){if(id===active)return;setBusy(true);setError("");try{await call("/v1/games/select","POST",{id});await onSelected(id);toast.success("게임 프로필을 적용했습니다. 시작/재개로 실행하세요.");}catch(e){setError(e instanceof Error?e.message:"게임 전환 실패");}finally{setBusy(false);}}
 async function add(){setBusy(true);setError("");try{const r=await call("/v1/games","POST",{name,window_title:title}) as {game:Game};setGames(g=>[...g,r.game]);await call("/v1/games/select","POST",{id:r.game.id});await onSelected(r.game.id);setAdding(false);setName("");setTitle("");toast.success("게임을 추가하고 독립 프로필을 적용했습니다.");}catch(e){setError(e instanceof Error?e.message:"게임 추가 실패");}finally{setBusy(false);}}
 return <section className="game-tabs" aria-label="게임 선택"><div className="game-tabs-heading"><h3>게임</h3><span>{online?"게임별 설정·객체 기록·통계":"Agent 연결 후 추가·선택"}</span></div><div className="game-tab-row" role="tablist" aria-label="게임 프로필">{games.map(g=><button key={g.id} role="tab" aria-selected={g.id===active} disabled={!online||busy} className={`game-tab ${g.id===active?"selected":""}`} onClick={()=>void select(g.id)}>{g.name}</button>)}<button className="game-add button secondary" disabled={!online||busy} onClick={()=>setAdding(v=>!v)}><Plus size={16}/>추가</button></div>{adding&&<form className="game-add-form" onSubmit={e=>{e.preventDefault();void add();}}><label>게임 이름<input aria-label="추가할 게임 이름" autoFocus maxLength={80} required value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>게임 창 제목<input aria-label="추가할 게임 창 제목" maxLength={120} value={title} disabled={busy} placeholder="실제 창 제목 일부 (설정에서 변경 가능)" onChange={e=>setTitle(e.target.value)}/></label><div><button className="button primary" disabled={busy||!name.trim()}>{busy?<Loader2 size={16} className="spin"/>:<Plus size={16}/>}추가 및 적용</button><button type="button" className="text-button" disabled={busy} onClick={()=>setAdding(false)}>취소</button></div><p className="live-help">빈 범용 프로필로 시작합니다. HUD·이동 키·스킬·OpenCV + Qwen 모델은 게임별로 설정하세요. 게임 전환 시 입력을 중단합니다.</p></form>}{error&&<p className="live-error" role="alert">{error}</p>}</section>;
}
