"use client";
import { useEffect, useState } from "react";
import { BarChart3, Download, Check } from "lucide-react";
import { toast } from "sonner";
type Summary={objects:Record<string,number>;encounters:number;actions:Record<string,Record<string,number>>;kills_confirmed:number;kills_estimated:number;events:Record<string,number>};
type Event={id:string;at:number;kind:string;action?:string;status?:string;track_id?:number;name?:string;reason?:string;source?:string;accepted?:boolean};
type Stats={profile:string;today:string;selected_day:string;total:Summary;day:Summary;days:string[];memory_records:number;current:{total:number};recent:Event[];kill_candidates:Event[];last_saved_at:number|null;error:string|null;storage:string;kill_detection:string};
const kinds:Record<string,string>={monster:"몬스터",npc:"NPC",item:"아이템",obstacle:"장애물",player:"플레이어",unknown:"미확정"};
const events:Record<string,string>={combat_rechecked:"전투 대상 재판정",input:"입력",hp_recheck:"HP 재확인",hp_recovered:"HP 복구",processing_halted:"처리 정지",objects_learned:"객체 학습",object_reclassified:"객체 분류 변경",kill_estimated:"추정 처치",kill_confirmed:"확인 처치"};
const actions:Record<string,string>={ATTACK:"기본 공격",USE_SKILL:"스킬",MOVE:"이동",TAKE:"줍기",USE_POTION:"물약",DODGE:"회피",CAST_BUFF:"버프",INTERACT:"상호작용"};
function num(value:number|undefined){return value===undefined?"—":value.toLocaleString("ko-KR");}
export default function StatisticsPanel({session,online}:{session:{url:string;token:string}|null;online:boolean}){
 const [data,setData]=useState<Stats|null>(null),[day,setDay]=useState(""),[range,setRange]=useState("total"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[updated,setUpdated]=useState<number|null>(null);
 async function call(path:string,body?:unknown){if(!session)throw new Error("Agent 연결이 필요합니다.");const response=await fetch(session.url+path,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${session.token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store",credentials:"omit",signal:AbortSignal.timeout(5000)});const result=await response.json() as Stats & {error?:string};if(!response.ok)throw new Error(result.error??"통계 읽기 실패");return result as Stats;}
 useEffect(()=>{let active=true,timer:ReturnType<typeof setTimeout>;setData(null);setUpdated(null);setError("");async function poll(){if(!session||!online)return;try{const next=await call('/v1/statistics'+(day?`?date=${encodeURIComponent(day)}`:""));if(active){setData(next);setUpdated(Date.now());setError("");}}catch(e){if(active)setError(e instanceof Error?e.message:"통계 연결 오류");}if(active)timer=setTimeout(()=>void poll(),2000);}void poll();return()=>{active=false;clearTimeout(timer);};},[session?.url,session?.token,day,online]);
 async function confirm(event:Event){setBusy(true);try{await call('/v1/statistics/kills/confirm',{id:event.id,confirmed:true});setData(await call('/v1/statistics'+(day?`?date=${encodeURIComponent(day)}`:"")));toast.success("처치 확인을 저장했습니다.");}catch(e){toast.error(e instanceof Error?e.message:"처치 확인 실패");}finally{setBusy(false);}}
 function exportData(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`${data.profile}-statistics-${data.selected_day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const summary=range==='total'?data?.total:data?.day;
 return <section className="panel statistics-panel" id="statistics" aria-label="게임 처리 통계"><div className="panel-heading"><h2><BarChart3 size={18}/>게임 통계</h2><span className="small-label">{data?.profile??"Agent 연결 대기"} · 재시작 후 유지</span></div><div className="live-body"><div className="statistics-toolbar"><div className="statistics-range"><button className={`button ${range==='total'?'primary':'secondary'}`} onClick={()=>setRange('total')}>전체 누적</button><button className={`button ${range==='day'?'primary':'secondary'}`} onClick={()=>setRange('day')}>날짜별</button>{range==='day'&&<input aria-label="통계 날짜" type="date" value={day||data?.today||""} onChange={e=>setDay(e.target.value)}/>}</div><button className="button secondary" disabled={!data} onClick={exportData}><Download size={15}/>통계 내보내기</button></div>
 {!session&&<p className="live-help">Agent에 자동으로 연결되면 실제 누적 통계를 불러옵니다.</p>}{error&&<p className="live-error" role="alert">{error}</p>}
 <div className="statistics-cards">{[{label:"확인된 처치 · 사용자 확인",n:summary?.kills_confirmed},{label:"추정 처치 · 미확인",n:summary?.kills_estimated},{label:"객체 조우 · 추적 ID 기준",n:summary?.encounters},{label:"저장된 객체 학습 기록",n:data?.memory_records}].map(v=><div key={v.label}><span>{v.label}</span><strong>{num(v.n)}</strong></div>)}</div>
 <p className="live-help">현재 화면 객체 {num(online?data?.current.total:undefined)}개. 누적 조우는 같은 추적 ID를 매 프레임 중복 집계하지 않습니다. 추적이 끊겨 새 ID가 생기면 같은 객체가 다시 집계될 수 있습니다.</p>
 <div className="statistics-columns"><div><h3>객체 유형별 집계</h3><div className="object-count-bars">{Object.entries(kinds).map(([kind,label])=><div key={kind}><span>{label}</span><div><i style={{width:`${summary?.encounters?(summary.objects[kind]??0)/summary.encounters*100:0}%`}}/></div><b>{num(summary?.objects[kind])}</b></div>)}</div><p className="live-help">미확정 객체가 분류되면 같은 조우 기록의 유형을 갱신합니다.</p></div><div><h3>입력·처리 결과</h3><div className="statistics-table"><table><thead><tr><th>명령</th><th>전송</th><th>차단/오류/취소</th></tr></thead><tbody>{Object.entries(actions).map(([action,label])=>{const value=summary?.actions[action];return <tr key={action}><td>{label}</td><td>{num(summary?value?.sent??0:undefined)}</td><td>{num(summary?(value?.blocked??0)+(value?.failed??0)+(value?.cancelled??0):undefined)}</td></tr>;})}</tbody></table></div><p className="live-help">HP 재확인 {num(summary?summary.events.hp_recheck??0:undefined)} · 복구 {num(summary?summary.events.hp_recovered??0:undefined)} · 처리 정지 {num(summary?summary.events.processing_halted??0:undefined)}</p></div></div>
 <div className="kill-candidates"><h3>추정 처치 확인</h3><p className="live-help">공격 전송 후 중앙의 적이 2초 이상 미검출된 경우입니다. 화면 가림·인식 실패일 수 있어 자동으로 확정하지 않습니다. 실제 처치를 확인한 기록만 확인 버튼을 누르세요.</p>{data?.kill_candidates.length?data.kill_candidates.slice(0,8).map(e=><div className="kill-candidate" key={e.id}><span>TRACK {e.track_id} · {e.name||"몬스터"}<small>{new Date(e.at*1000).toLocaleString("ko-KR")}</small></span><button className="button secondary" disabled={!online||busy} onClick={()=>void confirm(e)}><Check size={14}/>실제 처치 확인</button></div>):<p className="live-help">미확인 추정 처치 기록이 없습니다.</p>}</div>
 <h3>최근 처리 이력</h3><div className="statistics-table history"><table><thead><tr><th>시간</th><th>처리</th><th>대상 / 결과</th></tr></thead><tbody>{data?.recent.length?data.recent.slice(0,15).map(e=><tr key={e.id}><td>{new Date(e.at*1000).toLocaleTimeString("ko-KR")}</td><td>{events[e.kind]??e.kind} {e.action?actions[e.action]??e.action:""}</td><td>{e.track_id?`TRACK ${e.track_id} · `:""}{e.accepted!==undefined?(e.accepted?"적대 몬스터 확인":"공격 제외"):e.status??e.reason??e.source??"저장"}</td></tr>):<tr><td colSpan={3}>저장된 처리 이력 대기</td></tr>}</tbody></table></div>
 <p className="live-help">게임별 {data?.storage??"statistics.sqlite3"}에 저장합니다. 통계에 프레임 이미지는 저장하지 않습니다. {updated?`최근 동기화 ${new Date(updated).toLocaleTimeString("ko-KR")}`:""}</p></div></section>;
}
